name: Rialto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73312
title: 'Thought-filled communications strategies & tactics. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a19589'
    - '#0490c7'
    - '#65a6d3'
    - '#99c3e2'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
