name: Rialto
favicon: null
layout_spectrum: 0.8633253786247224
typography_spectrum: 0.13675924320705235
title: 'Thought-filled communications strategies & tactics. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a19589'
    - '#0490c7'
    - '#65a6d3'
    - '#99c3e2'
  brandStrength: 1
  lightness: 0.4738358536269516
  saturation: 0.5570815161336213
  rhythmicContrast: 0.0968609731644392
purpose: []
